# Generated by Django 6.0.6 on 2026-06-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('to-do', 'To-do'), ('in-progress', 'In-progress'), ('review', 'Review'), ('done', 'Done')], default='to-do', max_length=20),
        ),
    ]
