# Generated by Django 6.0.6 on 2026-06-17 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_board_comment_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Board',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
